name: Node CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Login to Docker Hub
      run: docker login --username "${{ secrets.DOCKER_USERNAME }}" --password "${{ secrets.DOCKER_PASSWORD }}"
    - name: Build the Docker Image 
      run: docker build --tag imagehub360/employee-service:${GITHUB_REF##*/} .
    - name: Push the Docker Image 
      run: docker push imagehub360/employee-service:${GITHUB_REF##*/}   
      env:
        CI: true
